In [19]:
import numpy as np

np.random.seed(85)

result = []

for i in range(3):
  a = np.arange(1,46)
  np.random.shuffle(a)
  lotto = a[:6]
  result.append(lotto)

result_array = np.array(result)

print('第三轮乐透号码结果（列表）:\n', result)
print('\n二维数组 (shape (3, 6)):\n', result_array)
print('数组形状：', result_array.shape)

第三轮乐透号码结果（列表）:
 [array([22,  9, 15, 44, 39, 37]), array([ 7, 31, 24, 40, 11, 16]), array([ 8,  3, 23, 40, 38, 32])]

二维数组 (shape (3, 6)):
 [[22  9 15 44 39 37]
 [ 7 31 24 40 11 16]
 [ 8  3 23 40 38 32]]
数组形状： (3, 6)


In [20]:
shape = (3,3,6)
A1 = np.random.randint(0,21,shape)
print(A1)


shape = (5,6)
A2 = np.random.randint(0,101,shape)
print(A2)

[[[15  5  1 12 19 12]
  [16  4 19 16 18 15]
  [ 5  3 11  1 20  9]]

 [[ 5 10  8  5  8 17]
  [ 4 17 14  2  0 18]
  [15 20 15  8  9  8]]

 [[ 0 11  6  4  8  3]
  [ 7  6 18  4  7  4]
  [13  3 20  3  1  8]]]
[[51 41 43 88 80 72]
 [43 41 69 65 72 91]
 [89 89 26 13 59 24]
 [ 2 54 31 76 85 87]
 [46 25 48 95 24 50]]


In [21]:
temp = np.arange(48)
arr1 = temp.reshape(4,3,4)
print(arr1)


arr2 = temp.reshape(6,8)
print(arr2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]
